import { useState, useRef, useEffect, useCallback } from "react";
import { AlertTriangle, Loader2 } from "lucide-react";
import { Button } from "@/components/ui/button";
import { Checkbox } from "@/components/ui/checkbox";
import { useAuth } from "@clerk/react";

const API = import.meta.env.VITE_API_URL ?? "";

interface AIScripterEuaModalProps {
  onAccepted: () => void;
}

export function AIScripterEuaModal({ onAccepted }: AIScripterEuaModalProps) {
  const { getToken } = useAuth();
  const [scrolledToBottom, setScrolledToBottom] = useState(false);
  const [checked, setChecked] = useState(false);
  const [submitting, setSubmitting] = useState(false);
  const [error, setError] = useState<string | null>(null);
  const bodyRef = useRef<HTMLDivElement>(null);

  const handleScroll = useCallback(() => {
    const el = bodyRef.current;
    if (!el) return;
    const atBottom = el.scrollHeight - el.scrollTop <= el.clientHeight + 32;
    if (atBottom) setScrolledToBottom(true);
  }, []);

  useEffect(() => {
    const el = bodyRef.current;
    if (!el) return;
    el.addEventListener("scroll", handleScroll, { passive: true });
    handleScroll();
    return () => el.removeEventListener("scroll", handleScroll);
  }, [handleScroll]);

  const handleAgree = async () => {
    if (!checked || !scrolledToBottom || submitting) return;
    setSubmitting(true);
    setError(null);
    try {
      const token = await getToken();
      const headers: Record<string, string> = {};
      if (token) headers["Authorization"] = `Bearer ${token}`;
      const res = await fetch(`${API}/api/user/aiscripter-agree`, {
        method: "POST",
        headers,
      });
      if (!res.ok) throw new Error(`Server error ${res.status}`);
      onAccepted();
    } catch (err) {
      setError(err instanceof Error ? err.message : "Failed to record agreement. Please try again.");
      setSubmitting(false);
    }
  };

  const canAgree = scrolledToBottom && checked && !submitting;

  return (
    <div className="fixed inset-0 z-50 flex items-center justify-center bg-black/80 backdrop-blur-sm p-4">
      <div className="bg-card border border-border rounded-2xl shadow-2xl w-full max-w-2xl flex flex-col max-h-[90vh]">
        <div className="flex items-start gap-3 px-6 pt-6 pb-4 border-b border-border flex-shrink-0">
          <div className="h-10 w-10 rounded-full bg-yellow-500/15 border border-yellow-500/30 flex items-center justify-center flex-shrink-0 mt-0.5">
            <AlertTriangle className="h-5 w-5 text-yellow-500" />
          </div>
          <div>
            <h2 className="text-lg font-bold text-foreground">AIScripter — End User Agreement</h2>
            <p className="text-sm text-muted-foreground mt-0.5">
              Please read and accept before continuing.
            </p>
          </div>
        </div>

        <div ref={bodyRef} className="flex-1 overflow-y-auto px-6 py-5 space-y-5 text-sm leading-relaxed">
          <section>
            <h3 className="font-semibold text-foreground mb-2">About AIScripter — Separate Application Required</h3>
            <p className="text-muted-foreground">
              AIScripter connects to a separate application that runs locally on your computer. It must be downloaded and
              launched before this feature can be used. It starts a local HTTP server on port 7860. Your video data is
              processed entirely on your own hardware — nothing is transmitted to any external server during script generation.
            </p>
          </section>

          <section>
            <h3 className="font-semibold text-foreground mb-2">End User Agreement</h3>
            <ul className="mt-2 space-y-2 text-muted-foreground list-disc list-inside">
              <li><strong className="text-foreground">AI-generated content.</strong> Scripts are machine-generated. Accuracy cannot be guaranteed. Always review before use.</li>
              <li><strong className="text-foreground">Experimental tool.</strong> AIScripter is a beta feature provided on an <em>as-is</em> basis.</li>
              <li><strong className="text-foreground">No warranties.</strong> The developer makes no warranties regarding quality, accuracy, or fitness for any purpose.</li>
              <li><strong className="text-foreground">Local processing.</strong> All video analysis occurs on your own machine. You are responsible for the content you process.</li>
              <li><strong className="text-foreground">No support guarantee.</strong> Support is provided on a best-effort basis.</li>
            </ul>
          </section>

          <section>
            <h3 className="font-semibold text-foreground mb-2">Liability Disclaimer</h3>
            <p className="text-muted-foreground">
              The developer is not responsible for any outputs generated by AIScripter, including physical discomfort, device
              damage, data loss, or any other harm. AI-generated haptic scripts may contain patterns unsuitable for your device.
              Always review scripts before use. To the fullest extent permitted by law, the developer disclaims all liability.
            </p>
          </section>

          <section className="rounded-lg border border-yellow-500/30 bg-yellow-500/5 p-4">
            <h3 className="font-semibold text-yellow-500 mb-2 flex items-center gap-2">
              <AlertTriangle className="h-4 w-4" />
              Content Warning
            </h3>
            <ul className="mt-2 space-y-1.5 text-muted-foreground text-sm list-disc list-inside">
              <li>You are 18 years of age or older (or the age of majority in your jurisdiction).</li>
              <li>You understand the nature of the content this tool is designed to produce.</li>
              <li>You are accessing this feature voluntarily and in a private capacity.</li>
              <li>Generated scripts are for personal use only and must not be redistributed commercially.</li>
              <li>You will only process video content that you have the legal right to use.</li>
            </ul>
          </section>

          <section>
            <h3 className="font-semibold text-foreground mb-2">Privacy</h3>
            <p className="text-muted-foreground">
              Video analysis and script generation requests are processed entirely by the AIScripter application running on your
              own computer. They are not transmitted to, logged by, or stored on any external server. Your content remains private.
            </p>
          </section>

          <p className="text-xs text-muted-foreground text-center pt-2 pb-1 border-t border-border">
            — End of agreement —
          </p>
        </div>

        <div className="px-6 py-4 border-t border-border flex-shrink-0 space-y-4">
          {!scrolledToBottom && (
            <p className="text-xs text-muted-foreground text-center">
              Scroll to the bottom to enable the agreement checkbox.
            </p>
          )}
          <div className="flex items-start gap-3">
            <Checkbox
              id="aiscripter-eua-checkbox"
              checked={checked}
              onCheckedChange={(val) => setChecked(!!val)}
              disabled={!scrolledToBottom}
              className="mt-0.5"
            />
            <label
              htmlFor="aiscripter-eua-checkbox"
              className={`text-sm leading-snug cursor-pointer select-none ${
                scrolledToBottom ? "text-foreground" : "text-muted-foreground/50 cursor-not-allowed"
              }`}
            >
              I have read and agree to the End User Agreement, the liability disclaimer, and the content warning above.
              I confirm I am 18 years of age or older.
            </label>
          </div>
          {error && <p className="text-xs text-destructive">{error}</p>}
          <div className="flex justify-end">
            <Button onClick={handleAgree} disabled={!canAgree} className="gap-2">
              {submitting ? (
                <><Loader2 className="h-4 w-4 animate-spin" />Saving…</>
              ) : (
                "I Agree — Continue to AIScripter"
              )}
            </Button>
          </div>
        </div>
      </div>
    </div>
  );
}
