kind = "api"
previewPath = "/api-legacy/"
title = "API Server (legacy)"
version = "1.0.0"
id = "3B4_FFSkEVBkAeYMFRJ2e"

[[services]]
localPort = 8080
name = "API Server"
paths = ["/api-legacy/"]

[services.development]
run = "fuser -k 8080/tcp || true && pnpm --filter @workspace/api-server run dev"
